baseURL = "https://example.com"
languageCode = "jp"
defaultContentLanguage = "jp"
title = "gamecolony OHC"
theme = "cayman-hugo-theme"

[params]
  # Header text, can be markdown
  project_name = "gamecolony OHC"
  project_tagline = "OHC専用 discoud bot 紹介ページ"